//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mylibrary
    {
        public int ID { get; set; }
        public string KitapAdi { get; set; }
        public string Yazar { get; set; }
        public Nullable<int> SayfaNo { get; set; }
        public string Turu { get; set; }
        public string Yayinevi { get; set; }
        public Nullable<System.DateTime> AldigimTarih { get; set; }
        public Nullable<bool> Okundu { get; set; }
    }
}
